resolver: lts-23.28

allow-newer: true
allow-newer-deps:
  - storable-offset

packages:
  - brillo
  - brillo-algorithms
  - brillo-examples
  - brillo-export
  - brillo-juicy
  - brillo-rendering

ghc-options:
  "$locals": -Wall -Werror -Wunused-matches -Wunused-imports -Wname-shadowing -Wunused-packages

extra-deps:
  - storable-offset-0.1.0.0
  - webp-0.1.2.0

  - github: ad-si/FULE
    commit: c2546b4a6c82ce2bc35d8b1ef1e558b0dd560e01

  - github: dpwiz/freetype2
    commit: d2acf926b5c448d8edd60e322862adcf2dbe9146
